In [3]:
# Customer Churn Analysis
# Capstone Project - Pattern 1
# Domain: Telecommunications

import pandas as pd
import numpy as np

print("Customer Churn Analysis Project")
print("Libraries imported successfully!")

Customer Churn Analysis Project
Libraries imported successfully!

In [4]:
import os

print(os.getcwd())
print(os.listdir("../data"))

C:\Users\acer\PycharmProjects\Capstone_Customer_Churn\notebooks
['WA_Fn-UseC_-Telco-Customer-Churn.csv']

In [5]:
df = pd.read_csv("../data/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
# Check the dataset size
print("Dataset Shape:", df.shape)

# Check all column names
print("\nColumn Names:")
print(df.columns.tolist())

# Check data types and non-null values
print("\nDataset Information:")
df.info()

# Check statistical summary
print("\nNumerical Summary:")
df.describe()

Dataset Shape: (7043, 21)

Column Names:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

Numerical Summary:

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [7]:
# Check the data type of each column
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [9]:
DDdf.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
# Check blank spaces in TotalCharges
(df["TotalCharges"].astype(str).str.strip() == "").sum()

np.int64(11)

In [12]:
# Convert blank spaces into missing values
df["TotalCharges"] = df["TotalCharges"].str.strip().replace("", np.nan)

# Check missing values again
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [13]:
# Check the missing values in TotalCharges only
df["TotalCharges"].isnull().sum()

np.int64(11)

In [14]:
# View rows where TotalCharges is missing
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [15]:
# Check tenure for rows with missing TotalCharges
df.loc[df["TotalCharges"].isnull(), ["tenure", "TotalCharges"]]

      tenure TotalCharges
488        0          NaN
753        0          NaN
936        0          NaN
1082       0          NaN
1340       0          NaN
3331       0          NaN
3826       0          NaN
4380       0          NaN
5218       0          NaN
6670       0          NaN
6754       0          NaN

In [16]:
# Replace missing TotalCharges with 0
df["TotalCharges"] = df["TotalCharges"].fillna(0)

# Verify missing values are handled
print("Missing TotalCharges:", df["TotalCharges"].isnull().sum())

# Check data type
print("TotalCharges data type:", df["TotalCharges"].dtype)

Missing TotalCharges: 0
TotalCharges data type: object

In [17]:
# Convert TotalCharges to numeric format
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"])

# Verify the data type
print("TotalCharges data type:", df["TotalCharges"].dtype)

# Check missing values again
print("\nMissing Values:")
print(df.isnull().sum().sum())

# Check dataset shape
print("\nFinal Dataset Shape:", df.shape)

TotalCharges data type: float64

Missing Values:
0

Final Dataset Shape: (7043, 21)

In [18]:
# Save the cleaned dataset
df.to_csv("../data/cleaned_customer_churn.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [19]:
# Business Question 1: Customer Count and Churn

total_customers = len(df)

churned_customers = (df["Churn"] == "Yes").sum()

not_churned_customers = (df["Churn"] == "No").sum()

print("Total Customers:", total_customers)
print("Churned Customers:", churned_customers)
print("Customers Retained:", not_churned_customers)

Total Customers: 7043
Churned Customers: 1869
Customers Retained: 5174

In [20]:
# Business Question 2: Churn and Retention Rate

churn_rate = (churned_customers / total_customers) * 100
retention_rate = (not_churned_customers / total_customers) * 100

print("Customer Churn Rate:", round(churn_rate, 2), "%")
print("Customer Retention Rate:", round(retention_rate, 2), "%")

Customer Churn Rate: 26.54 %
Customer Retention Rate: 73.46 %

In [21]:
# Business Question 3: Churn by Contract Type

contract_churn = df.groupby("Contract")["Churn"].value_counts().unstack(fill_value=0)

print("Customer Churn by Contract Type:")
print(contract_churn)

Customer Churn by Contract Type:
Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48

In [22]:
# Business Question 4: Average Monthly Charges

avg_charges = df.groupby("Churn")["MonthlyCharges"].mean()

print("Average Monthly Charges by Churn Status:")
print(avg_charges.round(2))

Average Monthly Charges by Churn Status:
Churn
No     61.27
Yes    74.44
Name: MonthlyCharges, dtype: float64

In [23]:
# Business Question 5: Average Tenure by Churn Status

avg_tenure = df.groupby("Churn")["tenure"].mean()

print("Average Customer Tenure by Churn Status:")
print(avg_tenure.round(2))

Average Customer Tenure by Churn Status:
Churn
No     37.57
Yes    17.98
Name: tenure, dtype: float64

In [24]:
# Business Question 6: Churn by Internet Service

internet_churn = df.groupby("InternetService")["Churn"].value_counts().unstack(fill_value=0)

print("Churn by Internet Service:")
print(internet_churn)

Churn by Internet Service:
Churn              No   Yes
InternetService
DSL              1962   459
Fiber optic      1799  1297
No               1413   113

In [25]:
# Create a derived column for customer tenure groups

df["TenureGroup"] = pd.cut(
    df["tenure"],
    bins=[-1, 12, 24, 48, 72],
    labels=["0-12 Months", "13-24 Months", "25-48 Months", "49-72 Months"]
)

# Check the new column
print(df[["tenure", "TenureGroup"]].head(10))

print("\nTenure Group Counts:")
print(df["TenureGroup"].value_counts().sort_index())

   tenure   TenureGroup
0       1   0-12 Months
1      34  25-48 Months
2       2   0-12 Months
3      45  25-48 Months
4       2   0-12 Months
5       8   0-12 Months
6      22  13-24 Months
7      10   0-12 Months
8      28  25-48 Months
9      62  49-72 Months

Tenure Group Counts:
TenureGroup
0-12 Months     2186
13-24 Months    1024
25-48 Months    1594
49-72 Months    2239
Name: count, dtype: int64

In [26]:
# Check outliers using the IQR method

columns_to_check = ["MonthlyCharges", "TotalCharges"]

for col in columns_to_check:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower_limit) | (df[col] > upper_limit)).sum()

    print(f"{col}")
    print("Lower Limit:", round(lower_limit, 2))
    print("Upper Limit:", round(upper_limit, 2))
    print("Outliers Count:", outliers)
    print()

MonthlyCharges
Lower Limit: -46.02
Upper Limit: 171.38
Outliers Count: 0

TotalCharges
Lower Limit: -4683.52
Upper Limit: 8868.67
Outliers Count: 0

In [27]:
# Numerical Exploratory Data Analysis (EDA)

numeric_columns = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

print("Numerical Statistics:")
print(df[numeric_columns].describe().round(2))

print("\nAverage Monthly Charges:", round(df["MonthlyCharges"].mean(), 2))
print("Median Monthly Charges:", round(df["MonthlyCharges"].median(), 2))
print("Average Total Charges:", round(df["TotalCharges"].mean(), 2))
print("Average Tenure:", round(df["tenure"].mean(), 2))

Numerical Statistics:
        tenure  MonthlyCharges  TotalCharges
count  7043.00         7043.00       7043.00
mean     32.37           64.76       2279.73
std      24.56           30.09       2266.79
min       0.00           18.25          0.00
25%       9.00           35.50        398.55
50%      29.00           70.35       1394.55
75%      55.00           89.85       3786.60
max      72.00          118.75       8684.80

Average Monthly Charges: 64.76
Median Monthly Charges: 70.35
Average Total Charges: 2279.73
Average Tenure: 32.37

In [28]:
# Final Data Quality Check

print("Final Dataset Shape:", df.shape)

print("\nTotal Duplicate Rows:", df.duplicated().sum())

print("\nTotal Missing Values:", df.isnull().sum().sum())

print("\nData Types:")
print(df.dtypes)

print("\nTenure Group Column Created:", "TenureGroup" in df.columns)

Final Dataset Shape: (7043, 22)

Total Duplicate Rows: 0

Total Missing Values: 0

Data Types:
customerID               str
gender                   str
SeniorCitizen          int64
Partner                  str
Dependents               str
tenure                 int64
PhoneService             str
MultipleLines            str
InternetService          str
OnlineSecurity           str
OnlineBackup             str
DeviceProtection         str
TechSupport              str
StreamingTV              str
StreamingMovies          str
Contract                 str
PaperlessBilling         str
PaymentMethod            str
MonthlyCharges       float64
TotalCharges         float64
Churn                    str
TenureGroup         category
dtype: object

Tenure Group Column Created: True

In [29]:
# Save the final cleaned dataset

df.to_csv("../data/cleaned_customer_churn.csv", index=False)

print("Final cleaned dataset saved successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Final cleaned dataset saved successfully!
Rows: 7043
Columns: 22